flowchart TD
subgraph "Main Memory (RAM)"
    subgraph SequenceFileParser
      StringSequenceBatchProducer
      StringBreakBatchProducer
      IntervalBatchProducer
    end

    subgraph SeqToBitsConverter
      InvalidCharsProducer
      BitsProducer
    end
    StringSequenceBatch(["
      StringSequenceBatch
      <i>
      seq (max_chars * 8)
      </i>
    "])
    InvalidCharsBatch(["
      InvalidCharsBatch
      <i>
      invalid_chars (max_chars * 8)
      </i>
    "])
    PositionsBatch(["
      PositionsBatch
      <i>
      positions (max_chars * 64)
      </i>
    "])
    IntervalBatch(["
      IntervalBatch
      <i>
      chars_before_newline (max_reads * 64)
      newlines_before_newfile (max_reads * 64)
      </i>
    "])
    IndexResultsBatch(["
      IndexResultsBatch
      <i>
      results (max_chars * 64)
      </i>
    "])
    StringBreakBatch(["
      CumulativePropertiesBatch
      <i>
      chars_before_newline (shared with IntervalBatch)
      string_size (64)
      </i>
    "])
    BitSeqBatch(["
      BitSeqBatch
      <i>
      bit_seq (max_chars * 2)
      </i>
    "])
    IndexPrintBatch(["
      IndexPrintBatch
      <i>
      results ((20 + 1) * 8 * max_chars)
      </i>
    "])
    PositionsBuilder
    IndexResultsPrinter
  end
  subgraph Disk
    FASTA{FASTA/Q Files}
    Indexes{Indexes}
  end
  subgraph "Gpu Memory (VRAM)"
    IndexSearcher
  end


  FASTA --> SequenceFileParser

  StringSequenceBatchProducer --- StringSequenceBatch
  StringBreakBatchProducer --- StringBreakBatch
  IntervalBatchProducer --- IntervalBatch
  InvalidCharsProducer --- InvalidCharsBatch
  BitsProducer --- BitSeqBatch
  PositionsBuilder --- PositionsBatch
  IndexSearcher --- IndexResultsBatch

  StringSequenceBatch --> SeqToBitsConverter
  StringBreakBatch --> PositionsBuilder
  IntervalBatch --> IndexResultsPrinter
  InvalidCharsBatch --> IndexResultsPrinter
  BitSeqBatch --> IndexSearcher
  PositionsBatch --> IndexSearcher
  IndexResultsBatch --> IndexResultsPrinter

  IndexResultsPrinter --- IndexPrintBatch
  IndexPrintBatch --> Indexes
