flowchart TD
    StringSequenceBatch(["
        StringSequenceBatch
        <i>
        buffers (max_characters * 64 + max_characters * 8)
        string_indexes ((num_readers + 1) * 64)
        cumulative_char_indexes ((num_readers + 1) * 64)
        char_indexes ((num_readers + 1) * 64)

        </i>
    "])
    CumulativePropertiesBatch(["
        CumulativePropertiesBatch
        <i>
        cumsum_positions_per_string (max_characters * 64)
        cumsum_string_lengths (max_characters * 64)

        </i>
    "])
    IntervalBatch(["
        IntervalBatch
        <i>
        string_before_newfile (max_characters * 64)
        string_lengths (max_characters * 64)

        </i>
    "])
    PositionsBatch(["
        Positions
        <i>
        (max_characters * 64)

        </i>
    "])
    BitSeqBatch(["
        BitSeqs
        <i>
        (max_characters * 2)

        </i>
    "])
    Results(["
        Results
        <i>
        (max_characters * 64)

        </i>
    "])
    InvalidCharsBatch(["
        InvalidChars
        <i>
        (max_characters * 8)

        </i>
    "])

    FASTA{FASTA}-->ContinuousSequenceFileParser
    subgraph ContinuousSequenceFileParser
        StringSequenceBatchProducer
        CumulativePropertiesBatchProducer
        IntervalBatchProducer
    end
    StringSequenceBatchProducer --- StringSequenceBatch
    CumulativePropertiesBatchProducer --- CumulativePropertiesBatch
    IntervalBatchProducer --- IntervalBatch
    ContinuousPositionsBuilder --- PositionsBatch
    ContinuousSeqToBitsConverter --- BitSeqsBatch
    ContinuousSeqToBitsConverter --- InvalidCharsBatch
    ContinuousSearcher --- Results

    StringSequenceBatch-->ContinuousSeqToBitsConverter
    CumulativePropertiesBatch-->ContinuousPositionsBuilder
    PositionsBatch --> ContinuousSearcher
    BitSeqsBatch --> ContinuousSearcher
    Results --> ContinuousResultsPrinter
    InvalidCharsBatch --> ContinuousResultsPrinter
    IntervalBatch --> ContinuousResultsPrinter

    ContinuousResultsPrinter--> ResultFiles{Results}
