flowchart LR
  subgraph CMake Hierarcy
    common_library_1([common_library_1]) --> common_libraries{{common_libraries}}
    common_library_2([common_library_2]) --> common_libraries

    google_test[/google_test/] --> test_main

    common_libraries --> test_main
    common_libraries --> main
  end

  subgraph Notation
    interface{{Interface}}
    library([library])
    executable[executable]
    ExternalDependency[/External Dependency/]
  end
